[package]
name = "git-ignore-utility"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gi"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
reqwest = { version = "0.11.23", features = ["blocking"] }
